### ISSUE TITLE
Compare to did:btco

### ISSUE THREAD

**Issue by brianorwhatever** [MicroStrategy/did-btc-spec#3]
I noticed a lack of comparison to the did:btco method, possibly because the authors aren't familiar.

I'd be interested in seeing a comparison. You can read more about the method [here](https://github.com/ordinalsreserve/did-btco/blob/main/spec.md)

**Comment by sangaman** [comment]
Thanks a lot, I hadn't come across this before. I will check it out and propose a comparison section here if you'd care to look over it.

**Comment by LeoBeb** [comment]
The main difference between did:btc and did:btco seems to be that did:btco inscribes the entire JSON DID document into a satoshi as an inscription and the identifier then uses that satoshi's ordinal number. Ours tries to minimize block space by making the documents dynamically created upon DID resolution.
I have added a reference in the specification document https://microstrategy.github.io/did-btc-spec/
