### ISSUE TITLE
Incorrect `id` properties in examples

### ISSUE THREAD

**Issue by brianorwhatever** [MicroStrategy/did-btc-spec#5]
In the [DID document examples](https://microstrategy.github.io/did-btc-spec/#example-a-did-btc-did-document-constructed-from-a-creation-transaction) the `id` properties aren't correct. The top level `id` should be the DID itself and not just the txref. The other items are also incorrect as they use the txref instead of the DID as well.

**Comment by sangaman** [comment]
Thanks for catching this, that's right. It was just an oversight in my part when constructing the examples.

**Comment by LeoBeb** [comment]
I am closing this as it was addressed.

**Comment by brianorwhatever** [comment]
No it was not. The id parameter in the linked example is not a proper uri. It should be the did itself

**Comment by LeoBeb** [comment]
Reopening until the PR is approved and merged.

**Comment by LeoBeb** [comment]
Merged the changes from #14. If further changes are required, please create a new PR directly. Thank you.
